### ISSUE TITLE
separator in context menu Firefox

### ISSUE THREAD

**Issue by krystian3w** [rNeomy/javascript-toggle-on-and-off#22]
Addon add our separator in right click menu from website elements

I must hide it in userChrome.css (`Firefox < 59`):
```css
#_479f0278-2c34-4365-b9f0-1d328d0f0a40__separator   { display:none !important; }
```
Updated CSS (`changed in Firefox 59 or 60`):

```css
#_479f0278-2c34-4365-b9f0-1d328d0f0a40_-menuitem-_separator  { display:none !important; }
```
